name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: login on DockerHub
      uses: actions/docker/login@master
      secrets: ["DOCKER_USERNAME", "DOCKER_PASSWORD"]
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: build the image
      uses: actions/docker/cli@master
      args: build -t drighart/workbench-python-base .
